name: 'cargo-auto-publish'
description: 'Automatically publish cargo crates in your repo when the version changes'
author: 'seunlanlege'

inputs:
  toml:
    description: space de-limited paths to Cargo.toml files of crates you want to auto-publish

runs:
  using: 'node12'
  main: 'dist/index.js'
